### ISSUE TITLE
Support php-amqplib 2.5

### ISSUE THREAD

**Issue by MariusKl** [gjedeer/celery-php#48]
Hey,

do you mind to add the newest release 2.0.2 to packagist.org to smooth the way the library can be used in other products?

In release 2.0.2 the version of "videlalvaro/php-amqplib" is still ">=2.4.0". I used 2.0.2 with 2.4.0, but after updating all third parties via composor the 2.5.0 version was installed which breaks one of our usecases because there is a problem with the backward compatibility. It is possible to fix the dependecy version for the next release? E.g. 2.5.x for 2.0.3 and so on? So it is possible to rely that the current release works with the dependency libaries.

**Comment by kalessil** [comment]
+1, I have to configure dependency using directly github for using release version.

**Comment by gjedeer** [comment]
Updating to support php-amqplib 2.5: sure, I'll do that with the next release

Packagist: since I seem to do everything composer-related wrong (judging by peoples' feedback from other issues), could you explain how to add this release? I just clicked "force update" on packagist and it didn't find the new release.

**Comment by kalessil** [comment]
@gjedeer : It's takes a while =), I'll provide support end of this week or next one.

**Comment by gjedeer** [comment]
@kalessil  Looking forward to your implementation!

**Comment by kalessil** [comment]
ping @gjedeer : I still here, but busy with work.

**Comment by gjedeer** [comment]
The branch "celery4" works with latest php-amqplib
